# Data Analysis Using NumPy

### NumPy's Superpowers:
- Faster than Python lists (C-optimized backend)
- Uses less memory (efficient storage)
- Supports vectorized operations (no explicit loops needed)
- Has built-in mathematical functions


In [20]:
#python zip

l1 = [1,2,3]
l2 = [4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

# Creating NumPy Arrays

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])    
print(arr1)    #prints 1D array


[1 2 3 4 5]


In [11]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)    #prints 2D array

[[1 2 3]
 [4 5 6]]


In [13]:
 type(arr1)

numpy.ndarray

In [16]:
print("Type:", type(arr1))

Type: <class 'numpy.ndarray'>


In [18]:
print("Shape:", arr1.shape)

Shape: (5,)


In [19]:
print("Shape:", arr2.shape)

Shape: (2, 3)


# Memory Efficiency – NumPy vs. Lists
Let's check memory consumption.


NumPy arrays use significantly less memory compared to Python lists.



In [21]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


# Vectorization – No More Loops!
NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.

In [59]:
list1=[1,2,3]

# Python list (loop-based)
list_squares = [x ** 2 for x in list1]

# NumPy (vectorized)
numpy_squares = arr1 ** 2

In [60]:
print(list_squares)

[1, 4, 9]


In [61]:
print(numpy_squares)

[ 1  4  9 16 25]


### ** Task: checking time 

In [62]:
import numpy as np
import time

In [63]:
# Python list
size = 1_000_000_0
list1 = list(range(size))

In [64]:
start = time.time()
list_squares = [x ** 2 for x in list1]
end = time.time()

In [65]:
print("Python list square time:", end - start)

Python list square time: 1.9078705310821533


In [70]:
start = time.time()
numpy_squares = arr1** 2
end = time.time()

In [71]:
print("NumPy list square time:", end - start)

NumPy list square time: 0.0002770423889160156


# NumPy vs. Python Lists – Performance Test
Let's compare Python lists with NumPy arrays using a simple example.

### Example 1: Adding Two Lists vs. NumPy Arrays

In [74]:
import numpy as np
import time

# Python list
size = 1_000_000_0
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)

Python list addition time: 1.9680147171020508
NumPy array addition time: 0.31064510345458984
