# Indexing and slicing
Lets now learn about indexing and slicing in Numpy

### Indexing (Same as Python Lists)

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


### Slicing (Extracting Parts of an Array)

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [6]:
print(arr[3:]);

[40 50]


In [8]:
sliced = arr[1:4]
sliced[0] = 999

In [9]:
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


###  Fancy Indexing & Boolean Masking
Fancy Indexing (Select Multiple Elements)

In [10]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


### Boolean Masking (Filter Data)

In [11]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


# Exercises for Practice

- Create a 3×3 array filled with random numbers and print its shape. 

In [14]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [15]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
np.shape(arr2)

(3, 3)

- Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [17]:
arr = np.array([1.1, 2.2, 3.3], dtype=np.float32)  
print(arr.dtype) 

float32


In [18]:
arr_int = arr.astype(np.int32) 
print(arr_int)  # [1 2 3]

[1 2 3]


- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]

In [20]:
arr = np.array([1,2,3,4,5,6])
idx = [0, 5, 4] 
print(arr[idx])  

[1 6 5]


- Reshape a 1D array of size 9 into a 3×3 matrix.

In [25]:
arr = np.array([4,5,6,7,8,5,8,7,6])
print(arr.shape, "\n")  

reshaped = arr.reshape((3,3)) 
print(reshaped)

(9,) 

[[4 5 6]
 [7 8 5]
 [8 7 6]]


In [26]:
flattened = arr.flatten()  
print(flattened)  

[4 5 6 7 8 5 8 7 6]


- Use boolean masking to filter numbers greater than 50 in an array.

In [27]:
arr = np.array([10,30,40,50,60,70])
mask = arr > 50  # Condition: values greater than 50
print(arr[mask]) 

[60 70]
